### PR TITLE
Switch to 16.04 + mitaka

### PR DESCRIPTION
**Pull request by matthewfischer**
Update container to use Ubuntu 16.04 and Mitaka keystone

### CODE REVIEW

**Comment by int32bit** [comment]
Thanks @matthewfischer , But I prefer using python image to reduce the image size, what do you think ?

**Comment by matthewfischer** [comment]
Absolutely fine with me. I just picked the first one I saw.

**Comment by int32bit** [comment]
@matthewfischer , when I started keystone service using `uwsgi`, I got `invalid user token` error, could you help me ? I have stuck in this issue for two nights, but no any idea!

**Comment by matthewfischer** [comment]
Sure Send me some more info via email

**Comment by int32bit** [comment]
Please go to #4 for detail, thanks!

**Comment by matthewfischer** [comment]
looks like this was updated already

**Pull request closed without merging**
